CREATE TABLE IF NOT EXISTS person (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    office VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);